[tool.poetry]
name = "protobuf-protoc-exe"
version = "27.1"
description = "Pip package to host the protoc binary"
authors = ["Robert Roos <robert.roos@demcon.com>"]
readme = "README.md"
packages = [
    { include = "protobuf_protoc_exe", from = "src" }
]
build = "package_build.py"

[tool.poetry.scripts]
protoc = { reference = "resources/protoc.exe", type = "file" }
# Unfortunately the build script is run after this script is installed, so an install step is needed first

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
