name: Build wheels

on:
  push:
    tags:
      - '*'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: |
          python -m pip install -U pip
          pip install build

      - run: python -m build

      - uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.os }}
          path: dist/*.whl
      - uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        # Also upload the source package, but only for one matrix entry:
        with:
          name: python-source-${{ matrix.os }}
          path: dist/*.tar.gz

  upload_wheels:
    name: Upload wheels to PyPi
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true
      - run: |
          ls -lah .
          ls -lah dist/

      -   uses: pypa/gh-action-pypi-publish@release/v1
          with:
            password: ${{ secrets.TEST_PYPI_API_TOKEN }}
            repository-url: https://test.pypi.org/legacy/
            verbose: true
