name: Build wheels

on: push

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: |
          python -m pip install -U pip
          pip install build

      - run: python -m build --wheel -v
      - if: matrix.os == 'ubuntu-latest'
        run: python -m build --sdist -v

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          retention-days: 1
          path: dist

  combine_artifacts:
    name: Combine artifacts
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:  # Download all artifacts so far
        path: dist
        merge-multiple: true
    - uses: actions/upload-artifact@v4
      with:
        name: package
        path: dist

  test_artifacts:
    name: Test distributions
    needs: combine_artifacts
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package
          path: dist
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      # Now install the package from the local wheels and try to use it:
      - run: |
          pip install --no-index --find-links ./dist protobuf_protoc_exe
          protoc --version
