#
# Periodic check of the official Protobuf repo that will mirror new releases with new tags here.
#

name: Protobuf Monitor

on: push

jobs:
    find_releases:
        name: Find releases
        runs-on: ubuntu-latest

        steps:

            - uses: actions/github-script@v7
              with:
                  script: |
                      const {data: releases_all } = await github.rest.repos.listReleases({
                          owner: "protocolbuffers",
                          repo: "protobuf",
                          per_page: 3,
                      });
                      
                      const {data: our_tags_all } = await github.rest.repos.listTags({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          per_page: 3,
                      });
                      console.log(our_tags_all)
                      const our_tags = our_tags_all.map(tag => tag["name"]);
                      console.log(our_tags)
                      
                      date_minimum = Date.parse("2024-09-01T00:00:00");
                      let releases = [];
                      for (release of releases_all) {
                          console.log(release);
                          console.log(release["created_at"]);
                          console.log(Date.parse(release["created_at"]));
                          if (Date.parse(release.created_at) >= date_minimum) {
                              releases.push(release.tag_name);
                          }
                      }
                      console.log(releases)
