#
# Periodic check of the official Protobuf repo that will mirror new releases with new tags here.
#

name: Protobuf Monitor

on: push

jobs:
    find_releases:
        name: Find releases
        runs-on: ubuntu-latest

        steps:

            - uses: actions/github-script@v7
              with:
                  script: |
                      const {data: releases_all } = await github.rest.repos.listReleases({
                          owner: "protocolbuffers",
                          repo: "protobuf",
                          per_page: 3,
                      });
                      console.log(releases_all);
                      date_minimum = new Date("2024-09-01T00:00:00");
                      let releases = [];
                      for (release in releases_all) {
                          if (new Date(release["created_at"]) >= date_minimum) {
                              releases.push(release["tag_name"]);
                          }
                      }
                      console.log(releases)
